'use client';

import { FormEvent, useMemo, useRef, useState } from 'react';

type Message={role:'user'|'assistant';content:string};
const labels={
  en:{button:'Ask coach AI',title:'Fitness concierge',welcome:'How can I help? Ask about services, online programs, booking, pricing or your next step.',placeholder:'Type your question…',send:'Send',voice:'Speak',stop:'Stop',disclaimer:'General site guidance only — not medical advice.'},
  fa:{button:'پرسش از دستیار AI',title:'دستیار فیتنس',welcome:'چطور می‌توانم کمک کنم؟ درباره خدمات، برنامه آنلاین، رزرو، هزینه‌ها یا قدم بعدی بپرسید.',placeholder:'سؤال خود را بنویسید…',send:'ارسال',voice:'صحبت',stop:'توقف',disclaimer:'راهنمای عمومی سایت است و جایگزین مشاوره پزشکی نیست.'},
  fr:{button:'Demander à l’IA',title:'Concierge fitness',welcome:'Comment puis-je vous aider ? Posez vos questions sur les services, le coaching en ligne, les réservations ou les tarifs.',placeholder:'Écrivez votre question…',send:'Envoyer',voice:'Parler',stop:'Arrêter',disclaimer:'Informations générales seulement — pas un avis médical.'},
  es:{button:'Preguntar a la IA',title:'Conserje fitness',welcome:'¿Cómo puedo ayudarte? Pregunta por servicios, coaching online, reservas, precios o el siguiente paso.',placeholder:'Escribe tu pregunta…',send:'Enviar',voice:'Hablar',stop:'Parar',disclaimer:'Orientación general del sitio; no sustituye consejo médico.'},
} as const;

export default function AIConcierge({lang}:{lang:'en'|'fa'|'fr'|'es'}){
  const t=labels[lang]; const [open,setOpen]=useState(false); const [value,setValue]=useState(''); const [messages,setMessages]=useState<Message[]>([{role:'assistant',content:t.welcome}]); const [loading,setLoading]=useState(false); const [listening,setListening]=useState(false); const recognitionRef=useRef<any>(null);
  const speechSupported=useMemo(()=>typeof window!=='undefined'&&Boolean((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition),[]);
  async function send(e?:FormEvent){e?.preventDefault();const text=value.trim();if(!text||loading)return;const next=[...messages,{role:'user' as const,content:text}];setMessages(next);setValue('');setLoading(true);try{const res=await fetch('/api/ai/concierge',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lang,messages:next.slice(-10)})});const data=await res.json();const reply=String(data.answer||data.error||'Sorry, I could not answer that right now.');setMessages(m=>[...m,{role:'assistant',content:reply}]);}catch{setMessages(m=>[...m,{role:'assistant',content:'Sorry, the assistant is temporarily unavailable.'}]);}finally{setLoading(false)}}
  function toggleVoice(){if(!speechSupported)return;if(listening){recognitionRef.current?.stop();return;}const Ctor=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;const r=new Ctor();recognitionRef.current=r;r.lang=lang==='fa'?'fa-IR':lang==='fr'?'fr-CA':lang==='es'?'es-ES':'en-CA';r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(ev:any)=>{const transcript=ev.results?.[0]?.[0]?.transcript||'';setValue(transcript)};r.start()}
  function speak(text:string){if(typeof window==='undefined'||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==='fa'?'fa-IR':lang==='fr'?'fr-CA':lang==='es'?'es-ES':'en-CA';window.speechSynthesis.speak(u)}
  return <div className={`ai-concierge ${open?'open':''}`}><button className="ai-launcher" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{t.button}</button>{open&&<div className="ai-panel" role="dialog" aria-label={t.title}><div className="ai-head"><div><strong>{t.title}</strong><small>24/7</small></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></div><div className="ai-messages">{messages.map((m,i)=><div key={i} className={`ai-message ${m.role}`}><p>{m.content}</p>{m.role==='assistant'&&<button className="speak-reply" onClick={()=>speak(m.content)} aria-label="Read reply aloud">◊</button>}</div>)}{loading&&<div className="ai-message assistant"><p>…</p></div>}</div><form className="ai-form" onSubmit={send}><input value={value} onChange={e=>setValue(e.target.value)} placeholder={t.placeholder}/>{speechSupported&&<button type="button" className="voice-btn" onClick={toggleVoice}>{listening?t.stop:t.voice}</button>}<button className="btn small" type="submit">{t.send}</button></form><small className="ai-disclaimer">{t.disclaimer}</small></div>}</div>;
}
