import Image from 'next/image';
import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {isLocale,type Locale} from '@/lib/i18n';
import {getExerciseForLocale,exerciseName,exerciseDescription,exerciseInstructions,exerciseTips,exerciseImage} from '@/lib/repdb';
import {siteUrl,brandName} from '@/lib/seo';

const ui={en:{back:'Exercise library',how:'How to perform',tips:'Technique tips',muscles:'Target muscles',equipment:'Equipment',level:'Level'},fa:{back:'آموزش حرکات',how:'روش اجرا',tips:'نکات تکنیکی',muscles:'عضلات هدف',equipment:'تجهیزات',level:'سطح'},fr:{back:'Bibliothèque',how:'Exécution',tips:'Conseils techniques',muscles:'Muscles ciblés',equipment:'Équipement',level:'Niveau'},es:{back:'Biblioteca',how:'Cómo realizarlo',tips:'Consejos técnicos',muscles:'Músculos objetivo',equipment:'Equipo',level:'Nivel'}};
function pretty(v?:string){return (v||'—').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}
export async function generateMetadata({params}:{params:Promise<{lang:string,slug:string}>}):Promise<Metadata>{const {lang,slug}=await params;if(!isLocale(lang))return{};const e=await getExerciseForLocale(slug,lang as Locale);if(!e)return{};const l=lang as Locale;const name=exerciseName(e,l),description=exerciseDescription(e,l);const path=`/${l}/exercises/${e.id}`;return{metadataBase:new URL(siteUrl),title:`${name} Exercise Guide | ${brandName}`,description:description.slice(0,160),alternates:{canonical:path,languages:{'en-CA':`/en/exercises/${e.id}`,fa:`/fa/exercises/${e.id}`,'fr-CA':`/fr/exercises/${e.id}`,es:`/es/exercises/${e.id}`,'x-default':`/en/exercises/${e.id}`}},openGraph:{title:name,description,url:path,type:'article'},robots:{index:true,follow:true}}}
export default async function ExerciseDetail({params}:{params:Promise<{lang:string,slug:string}>}){const {lang,slug}=await params;if(!isLocale(lang))notFound();const l=lang as Locale,e=await getExerciseForLocale(slug,l);if(!e)notFound();const t=ui[l],name=exerciseName(e,l),description=exerciseDescription(e,l),instructions=exerciseInstructions(e,l),tips=exerciseTips(e,l);const images=[exerciseImage(e.images?.flat?.start||e.images?.flat?.main),exerciseImage(e.images?.flat?.peak)].filter(Boolean) as string[];const schema={'@context':'https://schema.org','@type':'HowTo',name,description,image:images,totalTime:'PT10M',step:instructions.map((text,i)=>({'@type':'HowToStep',position:i+1,text})),inLanguage:l==='en'?'en-CA':l};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="page-hero"><div className="container"><Link className="text-link" href={`/${l}/exercises`}>← {t.back}</Link><h1>{name}</h1><p className="lead">{description}</p></div></section><section className="section"><div className="container exercise-detail-grid"><div className="exercise-visuals">{images.map((src,i)=><Image key={src} src={src} alt={`${name} ${i===0?'start':'peak'} position`} width={512} height={512} priority={i===0}/>)}</div><div><div className="exercise-facts"><div><small>{t.level}</small><strong>{pretty(e.difficulty)}</strong></div><div><small>{t.equipment}</small><strong>{pretty(e.equipment||(e.is_bodyweight?'bodyweight':''))}</strong></div><div><small>{t.muscles}</small><strong>{(e.primary_muscles||[]).map(pretty).join(', ')||'—'}</strong></div></div><h2>{t.how}</h2><ol className="instruction-list">{instructions.map((x,i)=><li key={i}>{x}</li>)}</ol>{tips.length>0&&<><h2>{t.tips}</h2><ul>{tips.map((x,i)=><li key={i}>{x}</li>)}</ul></>}<p className="repdb-credit">Exercise data &amp; images by <a href="https://repdb.co" target="_blank" rel="noreferrer">RepDB</a>.</p></div></div></section></>}
